### ISSUE TITLE
Complete guide

### ISSUE THREAD

**Issue by amitkarpe** [julienrbrt/chain-minimal#26]
Hi @julienrbrt,

I tried to find Complete guide to Create Your Validator and join existing testnet.
Can we have complete guide where create node (+validators) with genesis transaction?
and instructions where create validators and join the testnet after the genesis.

**Comment by julienrbrt** [comment]
I believe the best is to look at the Hub documentation: https://hub.cosmos.network/main/validators/validator-setup.html

**Comment by ahmadSaeedGoda** [comment]
@julienrbrt The link does not work!
![image](https://github.com/cosmosregistry/chain-minimal/assets/16512264/a9735040-bd3f-48c0-93ab-912f100fe1ef)

**Comment by julienrbrt** [comment]
Looks like they've updated their website. This was the content: https://github.com/cosmos/gaia/blob/legacy-docs/docs/docs/validators/validator-setup.md
